#! /bin/sh

picom --experimental-backends &
$HOME/.fehbg &
$HOME/.config/polybar/launch.sh
sxhkd &
udiskie --no-notify &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           7

bspc config top_padding          27
bspc config top_monocle_padding  -27

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
